name: Full Test Suite

on:
  workflow_dispatch:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'

jobs:
  test-all:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync

      - name: Run all tests (including E2E)
        run: uv run pytest tests/ -v --cov=src/azip --cov-report=term-missing --cov-report=html

      - name: Run mypy type checking
        run: uv run mypy src tests

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30
